In [2]:
import numpy as np
# Numpy Datatype
###Numpy.nd.array

a=np.array([3,5,4,5,7,7,78])
a

array([ 3,  5,  4,  5,  7,  7, 78])

In [3]:
type(a)

numpy.ndarray

In [4]:
print(a.shape)
print(a.size)
print(a.dtype)

(7,)
7
int32


In [7]:
b=np.array([[235,432,432],[245,45,452],[435,6,65]])
b

array([[235, 432, 432],
       [245,  45, 452],
       [435,   6,  65]])

In [19]:
print("Shape : ",b.shape)
print("Size : ",b.size)
print("dtype : " ,b.dtype)
print("length : ",len(b))
print("Type :" ,type(b))



Shape :  (3, 3)
Size :  9
dtype :  int32
length :  3
Type : <class 'numpy.ndarray'>


In [9]:
type(b)

numpy.ndarray

In [21]:
c=np.array([[[43,43],[65,54]],[[43,43],[54,54]],[[65,54],[54,54]]])

In [23]:
print("Shape : ",c.shape)
print("Size : ",c.size)
print("dtype : " ,c.dtype)
print("length : ",len(c))
print("Type :" ,type(c))
print(c.ndim)

Shape :  (3, 2, 2)
Size :  12
dtype :  int32
length :  3
Type : <class 'numpy.ndarray'>
3


In [24]:
'''Array Operations
1. Item Accessing: Subscripting, Slicing
2. Item Assignment
3. Item Insertion
4. Item Deletion
5. Arithmetic'''

'Array Operations\n1. Item Accessing: Subscripting, Slicing\n2. Item Assignment\n3. Item Insertion\n4. Item Deletion\n5. Arithmetic'

In [25]:
b[0][0]

235

In [26]:
b

array([[235, 432, 432],
       [245,  45, 452],
       [435,   6,  65]])

In [39]:
#subscripting
[1st,2nd,3rd, .....,nth dim]
#subscripting 

array([432])

In [48]:

b[1,-3:]



array([245,  45, 452])

In [47]:
b[:,-2]

array([432,  45,   6])

In [50]:
b[:, -2:-1]

array([[432],
       [ 45],
       [  6]])

In [51]:
b

array([[235, 432, 432],
       [245,  45, 452],
       [435,   6,  65]])

In [60]:
b[2,-3: ].shape


(3,)

In [63]:
c([[[100,110,130,140],[145,122,19,12],[16,15,11,18]],[[10,11,13,14],[45,22,9,2],[6,5,1,8]]])

TypeError: 'numpy.ndarray' object is not callable

In [64]:
print(b[-1:,:])
print(c[:1,:2:1])
print(c)

[[435   6  65]]
[[[43 43]
  [65 54]]]
[[[43 43]
  [65 54]]

 [[43 43]
  [54 54]]

 [[65 54]
  [54 54]]]


In [65]:
b

array([[235, 432, 432],
       [245,  45, 452],
       [435,   6,  65]])

In [67]:
b[1,2]=90
b

array([[235, 432, 432],
       [245,  45,  90],
       [435,   6,  65]])

In [70]:
#Intertion
a=np.append(a,80)

In [71]:
a

array([ 3,  5,  4,  5,  7,  7, 78, 80])

In [74]:
np.append(b, [[9,90,999]], axis =0)#axis =0-> Row ,1-> Col

array([[235, 432, 432],
       [245,  45,  90],
       [435,   6,  65],
       [  9,  90, 999]])

In [75]:
np.append(b, [[9],[90],[900]],axis=1)

array([[235, 432, 432,   9],
       [245,  45,  90,  90],
       [435,   6,  65, 900]])

In [80]:
#deletion
b1=b.copy()

In [82]:
np.delete(b1,0,axis=0)

array([[245,  45,  90],
       [435,   6,  65]])

In [83]:
#Arithmetic Operations

In [84]:
b1-20

array([[215, 412, 412],
       [225,  25,  70],
       [415, -14,  45]])

In [86]:
b1-40

array([[195, 392, 392],
       [205,   5,  50],
       [395, -34,  25]])

In [88]:
#array manipulation
arr.reshape()
b1.reshape(2,6,1)

NameError: name 'arr' is not defined

In [90]:
b1.reshape(2,6,1,1)

ValueError: cannot reshape array of size 9 into shape (2,6,1,1)

In [91]:
b1

array([[235, 432, 432],
       [245,  45,  90],
       [435,   6,  65]])

In [92]:
b.dtype

dtype('int32')

In [93]:
b.astype(float)

array([[235., 432., 432.],
       [245.,  45.,  90.],
       [435.,   6.,  65.]])

In [95]:
b1.astype('unit16')

TypeError: data type 'unit16' not understood

In [96]:
##np.array
##np.arange     -> array version of range func, also allows float
##np.linspace() -> number of items/ start ,end, no. of items
##np.ones()     -> generate all values
##np.zeros()    -> 

In [97]:
np.ones((3,4),dtype='int')*5

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])